/* Presenter start page: recommended click path (mirrors the spec's demo script), controls, reset. */
(function () {
  var tx = App.tx, ic = App.ic;
  function name(id) { var m = App.member(id); return m ? m.name : id; }
  function done(n) {
    var ts = App.ts(), ev = ts.events, has = function (f) { return ev.some(f); };
    return ({
      1: has(function (e) { return e.type === "signup"; }),
      2: !!ts.outbox.run,
      3: has(function (e) { return e.type === "renewal" && e.src === "link"; }),
      5: has(function (e) { return e.type === "checkout" && !e.forced && !e.guest && e.where !== "kiosk"; }),
      6: has(function (e) { return e.type === "checkout" && e.forced; }),
      7: has(function (e) { return e.type === "setting" || e.type === "licFiled"; }),
      8: has(function (e) { return (e.type === "checkin" || e.type === "checkout") && e.where === "kiosk"; })
    })[n] || false;
  }
  function render() {
    var t = App.ten(), other = App.tkey() === "guayama" ? "salinas" : "guayama", od = window.RC_DATA[other];
    var lm = t.linkMember, dk = t.deskDemo;
    var extra = {
      1: '<div class="sl-links"><a class="btn btn-primary" href="signup.html">' + ic("user-plus", "i-sm") + tx("Abrir inscripción", "Open sign-up") + "</a></div>" +
        '<ul class="sl-beats"><li><strong>' + tx("Todos los campos vienen llenos", "Every field is prefilled") + "</strong> " + tx("(" + App.ten().demo.signup.name + "): solo toca «Continuar» en cada paso.", "(" + App.ten().demo.signup.name + "): just tap Continue on each step.") + "</li><li>" + tx("Error de 21+: toca «Mostrar error de edad» junto a la fecha de nacimiento; «Usar fecha válida» lo corrige.", "21+ error: tap “Show age error” by the date of birth; “Use a valid date” fixes it.") + "</li><li>" + tx("Relevo: marca «He leído y acepto» y toca «Toca para firmar» (español o inglés).", "Waiver: check “I have read and agree” and tap “Tap to sign” (Spanish or English).") + "</li><li>" + tx("Avisos: el SMS empieza desmarcado por cumplimiento; un toque lo marca.", "Notices: SMS starts unchecked for compliance; one tap checks it.") + "</li><li>" + tx("Pago: tarjeta de prueba y móvil de ATH Móvil ya escritos. ATH Móvil muestra la espera de aprobación.", "Payment: test card and ATH Móvil number already filled. ATH Móvil shows the approval wait.") + "</li></ul>",
      2: '<div class="sl-links"><a class="btn btn-primary" href="dashboard.html">' + ic("dashboard", "i-sm") + tx("Abrir el panel", "Open the dashboard") + '</a><a class="btn btn-secondary" href="outbox.html">' + ic("send", "i-sm") + tx("Bandeja de demo", "Demo outbox") + "</a></div>" +
        '<ul class="sl-beats"><li>' + tx("En el panel toca «Ejecutar recordatorios de hoy».", "On the dashboard tap “Run today's reminders”.") + "</li><li>" + tx("Abre el texto para ", "Open the text to ") + "<strong>" + name(lm) + "</strong>" + tx(" (vence mañana) y toca el enlace.", " (expires tomorrow) and tap the link.") + "</li></ul>",
      3: '<div class="sl-links"><a class="btn btn-primary" href="renew.html?m=' + lm + '&src=link&step=d1&ch=sms">' + ic("renew", "i-sm") + tx("Abrir el enlace de ", "Open the link for ") + App.first(name(lm)) + "</a></div>" +
        '<ul class="sl-beats"><li>' + tx("Todo ya lleno (miembro, tarjeta de prueba, PayPal, móvil de ATH), sin contraseña: solo toca.", "Everything prefilled (member, test card, PayPal, ATH number), no password: just tap.") + "</li><li>" + tx("ATH Móvil: «Aprueba en ATH Móvil» con 10 minutos en vivo; usa «Demo: simular aprobación».", "ATH Móvil: “Approve in ATH Móvil” with a live 10-minute countdown; use “Demo: simulate approval”.") + "</li><li>" + tx("PayPal o tarjeta: confirma al instante y permite auto-renovación.", "PayPal or card: confirms instantly and allows auto-renew.") + "</li></ul>",
      4: '<div class="sl-links"><a class="btn btn-primary" href="portal.html">' + ic("home", "i-sm") + tx("Portal del miembro", "Member portal") + '</a><a class="btn btn-secondary" href="card.html">' + ic("card", "i-sm") + tx("Tarjeta digital (QR)", "Digital card (QR)") + "</a></div>" +
        '<ul class="sl-beats"><li>' + tx("«Editar» en Mis datos abre el formulario ya lleno (municipio, contacto de emergencia, fecha de la licencia, idioma).", "“Edit” under My details opens the form already filled (town, emergency contact, license date, language).") + "</li><li>" + tx("«Mi licencia de armas»: número enmascarado (•••• últimos 4), calendario de avisos (enviados / próximos) y el interruptor «Renovación radicada» que los pone en pausa.", "“My gun license”: masked number (•••• last 4), reminder timeline (sent / upcoming) and the “Renewal filed” switch that pauses them.") + "</li></ul>",
      5: '<div class="sl-links"><a class="btn btn-primary" href="checkin.html">' + ic("login", "i-sm") + tx("Abrir recepción", "Open front desk") + "</a></div>" +
        '<p class="sl-hint">' + tx("La búsqueda ya tiene «" + App.ten().demo.desk + "»: un toque en el resultado lo abre. Las búsquedas recientes siguen debajo.", "The search already holds “" + App.ten().demo.desk + "”: one tap on the result opens it. Recent lookups stay below.") + '</p><ol class="sl-beats sl-num"><li><a href="checkin.html?m=' + dk[0] + '">' + name(dk[0]) + "</a> · " + tx("pasa", "cleared") + "</li><li><a href=\"checkin.html?m=" + dk[1] + '">' + name(dk[1]) + "</a> · " + tx("vencida → «Renovar ahora» → entra → «Invitado (no dispara)» (nombre ya escrito; sin licencia ni calibre) → «Registrar salida» (usa «Demo: simular 1 h 45 min» para ver la duración; su invitado sale con él)", "lapsed → “Renew now” → checked in → “Guest (no shooting)” (name prefilled; no license or caliber) → “Check out” (use “Demo: simulate 1 h 45 min” to show the duration; the guest leaves with him)") + "</li><li><a href=\"checkin.html?m=" + dk[2] + '">' + name(dk[2]) + "</a> · " + tx("relevo viejo → firma en la tableta", "old waiver → signs on the tablet") + "</li><li><a href=\"checkin.html?m=" + dk[3] + '">' + name(dk[3]) + "</a> · " + tx("licencia de armas vencida → rechazo en rojo con el motivo (no hay excepción)", "expired gun license → red refusal with the reason (no override)") + "</li><li><a href=\"checkin.html?m=" + App.ten().licToday + '">' + name(App.ten().licToday) + "</a> · " + tx("licencia vence hoy → aviso amarillo, sí puede entrar", "license expires today → yellow warning, may check in") + "</li></ol>",
      6: '<div class="sl-links"><a class="btn btn-primary" href="dashboard.html">' + ic("dashboard", "i-sm") + tx("Volver al panel", "Back to the dashboard") + '</a><a class="btn btn-secondary" href="visits.html">' + ic("history", "i-sm") + tx("Registro de visitas oficial", "Official visit log") + "</a></div>" +
        '<ul class="sl-beats"><li>' + tx("«En las instalaciones ahora»: quién está, desde qué hora, cuánto tiempo y con qué calibre.", "“On site now”: who, since when, how long and with which caliber.") + "</li><li>" + tx("«Licencias por vencer»: toca una banda para ver la lista.", "“Licenses expiring”: tap a band for the list.") + "</li><li>" + tx("Registro de visitas oficial: nombre, fecha, licencia (•••• últimos 4), calibre, entrada y salida; los invitados que no disparan salen con su insignia y «N/A — no dispara». «Exportar CSV» → copia oficial (número completo, solo el dueño, queda registrada) o de trabajo (enmascarada).", "Official visit log: name, date, license (•••• last 4), caliber, time in and out; non-shooting guests show their badge and “N/A — no shooting”. “Export CSV” → official copy (full number, owner only, logged) or working copy (masked).") + "</li><li>" + tx("Toca «Demo: simular cierre del día» → aviso de quién sigue registrado → «Forzar salida de todos»; el registro las marca como salida forzada.", "Tap “Demo: simulate closing time” → warning of who's still signed in → “Force check-out all”; the log flags them as forced.") + "</li></ul>",
      7: '<div class="sl-links"><a class="btn btn-primary" href="settings.html#recordatorios">' + ic("settings", "i-sm") + tx("Avisos y canales", "Reminders & channels") + '</a><a class="btn btn-secondary" href="checkin.html?m=' + dk[3] + '">' + ic("login", "i-sm") + App.first(name(dk[3])) + tx(" en recepción", " at the desk") + '</a><a class="btn btn-secondary" href="portal.html?m=' + dk[3] + '#licencia">' + ic("id", "i-sm") + tx("Su licencia en el portal", "Their license in the portal") + "</a></div>" +
        '<ul class="sl-beats"><li>' + tx("Licencia vencida, suspendida o revocada: siempre bloquea, sin ajuste ni excepción (Reglamento 9172).", "Expired, suspended or revoked license: always blocks, no setting or override (Reglamento 9172).") + "</li><li>" + tx("Canales: email, push y en la app activos; SMS opcional y apagado (las operadoras restringen mensajes de armas). Actívalo para ver el texto de 1 segmento en Mensajes.", "Channels: email, push and in-app on; SMS optional and off (carriers restrict firearms messaging). Turn it on to see the 1-segment text in Messages.") + "</li><li>" + tx("En el portal de " + App.first(name(dk[3])) + ": toca «Renovación radicada» → los avisos quedan «En pausa».", "In " + App.first(name(dk[3])) + "'s portal: tap “Renewal filed” → reminders show “Paused”.") + "</li></ul>",
      8: '<div class="sl-links"><a class="btn btn-primary" href="kiosk.html">' + ic("tablet", "i-sm") + tx("Abrir quiosco", "Open kiosk") + "</a></div>" +
        '<ul class="sl-beats"><li>' + tx("Toca el visor para «escanear», o «Usar mi teléfono»: el número y el código 4821 ya están escritos.", "Tap the viewfinder to “scan”, or “Use my phone number”: the number and code 4821 are already filled in.") + "</li><li>" + tx("«Registrar salida»: tarjeta o teléfono + código (ya llenos); muestra entrada, salida y duración.", "“Check out”: card or phone + code (prefilled); shows time in, time out and duration.") + "</li><li>" + tx("«Firmar el relevo»: nombre ya escrito y «Toca para firmar».", "“Sign the waiver”: name prefilled and “Tap to sign”.") + "</li></ul>",
      9: '<div class="sl-links"><a class="btn btn-primary" href="dashboard.html?tenant=' + other + '"><svg class="tenant-mark" style="width:20px;height:20px"><use href="#' + od.mark + '-inv"/></svg>' + tx("Cambiar a ", "Switch to ") + od.name + "</a></div>" +
        '<ul class="sl-beats"><li>' + tx("Recorre panel, recepción, miembros y portal: otra marca, otros miembros.", "Walk through dashboard, front desk, members and portal: another brand, other members.") + "</li></ul>"
    };
    var steps = App.STEPS.map(function (s) {
      var title = s.page === "salinas" ? tx("Cambiar a ", "Switch to ") + od.name : App.txa(s.t);
      var ok = done(s.n);
      return '<li class="sl-step' + (ok ? " is-done" : "") + '"><span class="sl-n">' + (ok ? ic("check", "i-sm") : s.n) + '</span><div class="sl-body"><div class="row between wrap" style="gap:8px"><h3>' + title + "</h3>" + (ok ? '<span class="badge badge--active">' + ic("check-circle") + tx("Hecho", "Done") + "</span>" : "") + "</div><p>" + App.txa(s.d) + "</p>" + (extra[s.n] || "") + "</div></li>";
    }).join("");
    return '<div class="start-page">' +
      '<header class="start-top"><a class="rc-logo" href="index.html"><svg><use href="#rc-mark"/></svg><span>Range Club</span></a>' + App.endorse(20, "endorse--hdr") + '<span class="badge badge--neutral start-proto-tag">' + tx("Prototipo navegable", "Clickable prototype") + "</span><span class=\"grow\"></span>" + App.langSeg() + "</header>" +
      '<div class="start-grid"><main class="start-main">' +
      '<div class="eyebrow">' + tx("Guion de demo · unos 15 minutos · en español", "Demo script · about 15 minutes · in Spanish") + "</div>" +
      "<h1>" + tx("Demo para administradores de clubes de tiro", "Demo for gun range administrators") + "</h1>" +
      '<p class="lead">' + tx("Sigue estos pasos en orden. Todos los campos ya vienen llenos con datos de ejemplo: solo toca los botones. Todo es ficticio y se guarda solo en este navegador: no hay servidor, no se envían mensajes y no se mueve dinero.", "Follow these steps in order. Every field is already filled with sample data: just tap the buttons. Everything is fictional and stays in this browser: no server, no messages sent and no money moved.") + "</p>" +
      '<div class="start-ctl-mobile">' + App.tenantSeg() + '<button type="button" class="btn btn-secondary btn-sm" data-act="resetDemo">' + ic("renew", "i-sm") + tx("Reiniciar demo", "Reset demo") + "</button></div>" +
      '<ol class="sl">' + steps + "</ol></main>" +
      '<aside class="start-side">' +
      '<section class="card card-pad stack-3"><h2 class="h3">' + tx("Controles", "Controls") + '</h2>' +
      '<div class="ctl"><div class="ctl-l">' + tx("Club (inquilino)", "Range (tenant)") + "</div>" + App.tenantSeg() + "</div>" +
      '<div class="pick is-on" style="cursor:default"><svg class="tenant-mark" style="width:36px;height:36px">' + App.mark() + '</svg><span class="grow"><strong>' + t.name + '</strong><span class="xs subtle" style="display:block">' + t.host + " · " + t.city + "</span></span></div>" +
      '<div class="ctl"><div class="ctl-l">' + tx("Idioma de la interfaz", "Interface language") + "</div>" + App.langSeg() + "</div>" +
      '<button type="button" class="btn btn-secondary btn-block" data-act="resetDemo">' + ic("renew", "i-sm") + tx("Reiniciar demo", "Reset demo") + "</button>" +
      '<p class="xs subtle">' + tx("Reinicia antes de cada presentación. El club y el idioma se recuerdan entre páginas.", "Reset before each presentation. Range and language are remembered across pages.") + "</p></section>" +
      '<section class="card card-pad stack-2"><h2 class="h3">' + tx("Fecha de la demo", "Demo date") + '</h2><p class="small">' + App.fdl(App.TODAY) + '</p><p class="xs subtle">' + tx("Estados calculados con gracia de " + t.grace + " días y edad mínima de " + t.minAge + " años.", "Statuses use a " + t.grace + "-day grace period and a minimum age of " + t.minAge + ".") + "</p></section>" +
      '<section class="card card-pad stack-2"><h2 class="h3">' + tx("Real vs. simulado", "Real vs. simulated") + '</h2><p class="small"><strong>' + tx("Funciona de verdad:", "Really works:") + "</strong> " + tx("aislamiento por club, invitados que disparan y que no disparan (cada uno con su fila en el registro oficial, entrada y salida), interfaz bilingüe, versiones y firma del relevo, ciclo de renovación y enlaces, reglas de entrada (licencia vencida, suspendida o revocada bloquea; vence hoy avisa), entrada y salida con calibre y duración, registro de visitas oficial (6 campos del Reglamento 9172) y su CSV (se genera en el navegador), salida forzada marcada, licencias enmascaradas (últimos 4), calendario de avisos y «Renovación radicada», canales de aviso, bandas de licencias, conteo de caracteres SMS, métricas.", "range isolation, shooting and non-shooting guests (each with its own official-log row, time in and out), bilingual UI, waiver versions and signing, renewal lifecycle and links, check-in rules (expired, suspended or revoked license blocks; expiring today warns), check-in and check-out with caliber and duration, official visit log (Reglamento 9172's 6 fields) and its CSV (generated in the browser), flagged forced check-out, masked licenses (last 4), reminder timeline and “Renewal filed”, reminder channels, license bands, SMS character count, metrics.") + '</p><p class="small"><strong>' + tx("Simulado:", "Simulated:") + "</strong> " + tx("email y texto (bandeja en pantalla), aprobación de ATH Móvil, PayPal sandbox, tareas programadas (botón de demo), subdominios por club, escaneo QR y código por texto (siempre 4821), hora de cierre (atajo «Simular cierre del día»), historial de días anteriores, números de licencia (LA-DEMO-…, ficticios; no se validan con la Policía; el cifrado y el registro de accesos son de producción), notificaciones push y en la app (vista previa). Todos los campos vienen llenos con datos ficticios.", "email and text (on-screen outbox), ATH Móvil approval, PayPal sandbox, scheduled jobs (demo button), per-range subdomains, QR scanning and texted code (always 4821), closing time (“Simulate closing time” shortcut), earlier days' history, license numbers (LA-DEMO-…, fictional; not verified with the Police; encryption and the access log are production features), push and in-app notifications (preview). Every field is prefilled with fictional data.") + "</p></section>" +
      '<section class="card card-pad stack-2"><h2 class="h3">' + tx("Todas las pantallas", "All screens") + '</h2><div class="all-links">' +
      [["dashboard.html", "dashboard", "Panel", "Dashboard"], ["checkin.html", "login", "Recepción", "Front desk"], ["members.html", "users", "Miembros", "Members"], ["outbox.html", "send", "Bandeja de demo", "Demo outbox"], ["signup.html", "user-plus", "Inscripción", "Sign-up"], ["renew.html", "renew", "Renovación", "Renewal"], ["portal.html", "home", "Portal", "Portal"], ["card.html", "card", "Tarjeta digital", "Digital card"], ["kiosk.html", "tablet", "Quiosco", "Kiosk"]].map(function (l) { return '<a href="' + l[0] + '">' + ic(l[1], "i-sm") + tx(l[2], l[3]) + "</a>"; }).join("") +
      "</div></section></aside></div>" +
      '<footer class="start-foot">' + App.endorse(24, "endorse--lg") + '<span class="xs subtle">' + tx("Range Club es un producto de Infante Automation.", "Range Club is a product of Infante Automation.") + "</span></footer></div>";
  }
  App.page({ render: render, title: function () { return tx("Demo para presentar", "Presenter start"); } });
})();
