/* Member portal (mobile): status, digital card, waiver/orientation/passes, household, auto-renew, messages, history. */
(function () {
  var tx = App.tx, ic = App.ic;
  function who() { var list = App.members(), id = App.q("m") || App.ts().current || App.ten().portalMember; var m = App.member(id, list) || App.member(App.ten().portalMember, list); return { list: list, m: m, p: App.primary(m, list) }; }
  /* profile fields: the member's own values, falling back to the club's fictional sample (RC_DATA.<club>.demo.profile) */
  function prof(p) { var d = App.ten().demo.profile; return { town: p.town || d.town, zip: p.zip || d.zip, emer: p.emer || d.emer }; }
  /* "Mi licencia de armas": masked number, expiry, renewal-filed toggle (pauses reminders) and the reminder timeline */
  function licSection(m) {
    var L = App.lic(m), ch = App.settings().licCh;
    if (!L.exp) return "";
    var chans = [ch.email ? "email" : "", ch.push ? "push" : "", ch.app ? tx("en la app", "in-app") : "", ch.sms && m.sms !== false ? tx("texto", "text") : ""].filter(Boolean).join(", ");
    var note = L.blocked ? '<div class="callout bad">' + ic("x-circle") + "<span>" + (L.band === "expired" ? tx("Vencida: no puedes tirar en el club hasta renovarla. Sin multa hasta el " + App.fd(L.graceEnd, "es") + ".", "Expired: you can't shoot at the range until it's renewed. No fine until " + App.fd(L.graceEnd, "en") + ".") : tx("Tu licencia no está vigente. Comunícate con la Policía de Puerto Rico.", "Your license isn't valid. Contact the Puerto Rico Police.")) + "</span></div>"
      : L.band === "today" ? '<div class="callout warn">' + ic("alert") + "<span>" + tx("Vence hoy. Desde mañana no podrás tirar hasta renovarla.", "Expires today. From tomorrow you can't shoot until it's renewed.") + "</span></div>"
      : L.band === "soon30" || L.band === "soon6" ? '<div class="callout">' + ic("info") + "<span>" + tx("Ya puedes renovarla (desde 6 meses antes del vencimiento).", "You can renew it now (from 6 months before it expires).") + "</span></div>" : "";
    return '<div id="licencia"><div class="sec-head"><div class="m-section-title">' + tx("Mi licencia de armas", "My gun license") + "</div>" + App.licBadge(m) + '</div><div class="m-card m-card-pad stack-3">' +
      '<div class="lic-sum"><div><div class="eyebrow">' + tx("Número", "Number") + '</div><div class="mono" style="font-weight:700" data-lic-masked>' + L.masked + '</div></div><div><div class="eyebrow">' + tx("Vence", "Expires") + '</div><div style="font-weight:700">' + App.fd(L.exp) + "</div></div></div>" + note +
      (L.band === "suspended" || L.band === "revoked" ? "" : '<div class="set-row" style="gap:10px"><div class="grow"><div style="font-weight:650">' + tx("Renovación radicada", "Renewal filed") + '</div><div class="xs subtle">' + tx("Márcalo cuando radiques la renovación: pausamos los avisos.", "Turn it on once you file the renewal: we pause the reminders.") + "</div></div>" + App.filedToggle(m) + "</div>") +
      '<div><div class="label">' + tx("Calendario de avisos", "Reminder timeline") + '</div><div class="xs subtle" style="margin-bottom:6px">' + tx("Por ", "By ") + chans + "</div>" + App.licTimelineHTML(m) + "</div>" +
      '<div class="xs subtle">' + tx("Solo guardamos el número (cifrado) y la fecha de vencimiento. Nunca fotos del carnet ni lista de armas.", "We only keep the number (encrypted) and expiry date. Never card photos or a firearms list.") + "</div></div></div>";
  }
  function render() {
    var t = App.ten(), w = who(), m = w.m, p = w.p, list = w.list, st = App.status(m, list), hh = App.household(p, list), pass = App.passes(m, list);
    var d = p.expires ? App.diff(p.expires, App.TODAY) : null, tr = t.tiers[p.tier];
    var banner = "";
    if (st === "grace" || st === "lapsed" || (st === "active" && d <= 30 && !p.autorenew)) {
      var head = st === "lapsed" ? tx("Tu membresía venció el ", "Your membership expired ") + App.fd(p.expires) : st === "grace" ? tx("En gracia hasta el ", "In grace until ") + App.fd(App.graceEnd(p, list)) : d === 0 ? tx("Vence hoy, ", "Expires today, ") + App.fd(p.expires) : d === 1 ? tx("Vence mañana, ", "Expires tomorrow, ") + App.fd(p.expires) : tx("Vence el ", "Expires ") + App.fd(p.expires);
      banner = '<div class="renew-banner' + (st === "lapsed" ? " is-bad" : "") + '">' + ic(st === "lapsed" ? "x-circle" : "clock", "i-lg") + '<div class="grow"><div style="font-weight:700;font-size:14.5px;line-height:19px">' + head + '</div><div class="small" style="color:var(--n-700)">' + App.tierName(p.tier) + " · " + App.money(tr.price) + '</div></div><a class="btn btn-primary btn-sm" href="renew.html?m=' + p.id + '&src=portal">' + tx("Renovar", "Renew") + "</a></div>";
    } else if (p.renewedAt) banner = '<div class="callout ok">' + ic("check-circle") + "<span>" + tx("Renovada hoy · activa hasta el ", "Renewed today · active until ") + "<strong>" + App.fd(p.expires) + "</strong></span></div>";
    var waiverOk = m.waiver && m.waiver.v === t.waiver.v, orientOk = m.orient && m.orient.exp >= App.TODAY;
    var okc = "color:var(--ok-700)", reqc = "color:var(--req-700)";
    var stc = { active: "var(--ok-700)", grace: "var(--warn-700)", lapsed: "var(--bad-700)", suspended: "var(--n-900)", pending: "var(--n-700)", cancelled: "var(--n-700)" }[st];
    var stats = '<div class="stat-grid">' +
      '<div class="stat"><div class="l">' + ic("card") + "<span>" + tx("Membresía", "Membership") + '</span></div><div class="v" style="color:' + stc + '">' + ic(App.STATUS[st][2]) + "<span>" + App.txa(App.STATUS[st]) + '</span></div><div class="s">' + (p.expires ? (st === "lapsed" ? tx("Venció ", "Expired ") : tx("Vence ", "Expires ")) + App.fd(p.expires) : "—") + "</div></div>" +
      '<div class="stat"><div class="l">' + ic("waiver") + "<span>" + tx("Relevo", "Waiver") + '</span></div><div class="v" style="' + (waiverOk ? okc : reqc) + '">' + ic(waiverOk ? "check-circle" : "alert") + "<span>" + (waiverOk ? tx("Firmado v", "Signed v") + t.waiver.v : tx("Firmar v", "Sign v") + t.waiver.v) + '</span></div><div class="s">' + (waiverOk ? tx("Versión actual · ", "Current version · ") + (m.waiver.lang === "en" ? tx("inglés", "English") : tx("español", "Spanish")) + " · " + App.fds(m.waiver.date) : tx("Fírmalo en la tableta de recepción", "Sign it on the front-desk tablet")) + "</div></div>" +
      '<div class="stat"><div class="l">' + ic("orientation") + "<span>" + tx("Orientación", "Orientation") + '</span></div><div class="v" style="' + (orientOk ? okc : reqc) + '">' + ic(orientOk ? "check-circle" : "alert") + "<span>" + (orientOk ? tx("Vigente", "Current") : m.orient ? tx("Vencida", "Expired") : tx("Pendiente", "Pending")) + '</span></div><div class="s">' + (orientOk ? tx("Hasta ", "Until ") + App.fd(m.orient.exp) : tx("Se completa en el club antes de tirar", "Completed at the range before shooting")) + "</div></div>" +
      '<div class="stat"><div class="l">' + ic("ticket") + "<span>" + tx("Pases de invitado", "Guest passes") + '</span></div><div class="v">' + pass[0] + ' <span class="s" style="font-size:13px;font-weight:500">' + tx("de " + pass[1] + " restantes", "of " + pass[1] + " left") + '</span></div><div class="s">' + tx("Se renuevan con tu membresía", "Reset when you renew") + "</div></div></div>";
    var hhHtml = hh.map(function (x) {
      var ok = x.waiver && x.waiver.v === t.waiver.v;
      return '<div class="list-row"><div class="avatar ' + (x.av || "av-1") + '">' + App.ini(x.name) + '</div><div class="grow"><div style="font-weight:600">' + x.name + '</div><div class="xs subtle">' + (x.id === p.id ? tx("Titular · paga el hogar", "Primary · pays for the household") : (x.gender === "f" ? tx("Adulta", "Adult") : tx("Adulto", "Adult")) + " · " + tx("21+ verificada", "21+ verified")) + "</div></div>" + (ok ? '<span class="badge badge--active">' + ic("check-circle") + tx("Al día", "Ready") + "</span>" : '<span class="badge badge--req">' + ic("waiver") + tx("Firmar v", "Sign v") + t.waiver.v + "</span>") + "</div>";
    }).join("");
    var ar = p.autorenew;
    var auto = '<div class="m-card m-card-pad" style="display:flex;gap:12px;align-items:flex-start"><button type="button" class="toggle' + (ar ? " is-on" : "") + '" role="switch" aria-checked="' + !!ar + '" data-act="toggleAuto" aria-label="' + tx("Auto-renovación", "Auto-renew") + '" style="margin-top:2px;flex:none"></button><div class="grow"><div style="font-weight:650">' + (ar ? tx("Auto-renovación activada · ", "Auto-renew is on · ") + (ar === "paypal" ? "PayPal" : tx("tarjeta", "card")) : tx("Auto-renovación desactivada", "Auto-renew is off")) + '</div><div class="small muted">' + (ar ? tx("Se renovará el " + App.fd(p.expires, "es") + " por " + App.money(tr.price) + ". Te avisamos 7 días antes. Cancela cuando quieras.", "Renews " + App.fd(p.expires, "en") + " for " + App.money(tr.price) + ". We notify you 7 days before. Cancel anytime.") : tx("Actívala con PayPal o tarjeta y no te preocupes más. Te avisamos antes de cada cobro. (ATH Móvil no permite pagos recurrentes.)", "Turn it on with PayPal or a card and never miss a renewal. We notify you before every charge. (ATH Móvil doesn't support recurring payments.)")) + "</div></div></div>";
    var ev = App.ts().events.filter(function (e) { return e.id === p.id || e.id === m.id; }).slice().reverse();
    var hist = ev.map(function (e) {
      if (e.type === "renewal") return '<div class="list-row">' + ic("receipt") + '<div class="grow"><div style="font-weight:600">' + tx("Pago", "Payment") + " · " + App.money(e.amount) + '</div><div class="xs subtle">' + tx("Hoy", "Today") + " · " + App.time(e.at) + " · " + ({ paypal: "PayPal", card: tx("Tarjeta", "Card"), ath: "ATH Móvil" }[e.method]) + '</div></div><span class="xs subtle mono">' + e.receipt + "</span></div>";
      if (e.type === "checkin") return '<div class="list-row">' + ic("login") + '<div class="grow"><div style="font-weight:600">' + tx("Visita", "Visit") + (e.guests && e.guests.length ? tx(" · con " + e.guests.length + " invitado(s)", " · with " + e.guests.length + " guest(s)") : "") + '</div><div class="xs subtle">' + tx("Hoy", "Today") + " · " + App.time(e.at) + "</div></div></div>";
      if (e.type === "waiver") return '<div class="list-row">' + ic("waiver") + '<div class="grow"><div style="font-weight:600">' + tx("Relevo firmado v", "Waiver signed v") + t.waiver.v + '</div><div class="xs subtle">' + tx("Hoy", "Today") + " · " + App.time(e.at) + "</div></div></div>";
      return "";
    }).join("") + (m.last && !ev.some(function (e) { return e.type === "checkin"; }) ? '<div class="list-row">' + ic("login") + '<div class="grow"><div style="font-weight:600">' + tx("Visita", "Visit") + '</div><div class="xs subtle">' + App.fdl(m.last) + "</div></div></div>" : "") +
      (p.pay || []).map(function (y) { return '<div class="list-row">' + ic("receipt") + '<div class="grow"><div style="font-weight:600">' + tx("Pago", "Payment") + " · " + App.money(y[1]) + '</div><div class="xs subtle">' + App.fd(y[0]) + " · " + ({ paypal: "PayPal", card: tx("Tarjeta", "Card"), ath: "ATH Móvil" }[y[2]]) + "</div></div></div>"; }).join("");
    var hour = new Date().getHours();
    var body = '<div class="m-content"><div class="p-greet"><div><div class="small muted">' + (hour < 12 ? tx("Buenos días", "Good morning") : hour < 18 ? tx("Buenas tardes", "Good afternoon") : tx("Buenas noches", "Good evening")) + '</div><h1 style="font-size:24px;line-height:30px">' + m.name + '</h1></div><div class="avatar avatar-lg ' + (m.av || "av-1") + '">' + App.ini(m.name) + "</div></div>" + banner +
      '<a class="dcard" href="card.html?m=' + m.id + '"><div class="top"><svg style="width:28px;height:28px">' + App.mark(true) + '</svg><span style="font-weight:700;font-size:14px">' + t.name + '</span><span class="grow"></span><span style="font-size:11px;font-weight:600;opacity:.85;letter-spacing:.06em">' + tx("MIEMBRO", "MEMBER") + '</span></div><div class="bottom"><div><div style="font-size:19px;font-weight:700;line-height:24px">' + m.name + '</div><div style="font-size:13px;opacity:.88;margin-top:2px">' + App.tierName(p.tier) + " · " + m.id + '</div><div style="margin-top:10px"><span class="badge" style="background:rgba(255,255,255,.95);color:' + stc + '">' + ic(App.STATUS[st][2]) + App.txa(App.STATUS[st]) + '</span></div></div><div class="qr"><img src="' + App.qr(m.id) + '" alt="QR"></div></div></a>' +
      '<div class="small muted" style="text-align:center;margin-top:-6px">' + tx("Toca la tarjeta para mostrarla en recepción", "Tap the card to show it at the front desk") + "</div>" + stats +
      '<div id="hogar"><div class="sec-head"><div class="m-section-title">' + tx("Mi hogar", "My household") + '</div><span class="small muted">' + hh.length + tx(" de ", " of ") + tr.hh + '</span></div><div class="m-card">' + hhHtml + "</div></div>" + auto +
      '<div id="perfil"><div class="sec-head"><div class="m-section-title">' + tx("Mis datos y avisos", "My details & notices") + '</div><button type="button" class="btn btn-secondary btn-sm" data-act="editProfile">' + ic("edit", "i-sm") + tx("Editar", "Edit") + '</button></div><div class="m-card"><div class="list-row">' + ic("home") + '<div class="grow"><div style="font-weight:600">' + tx("Municipio", "Town") + '</div><div class="xs subtle">' + App.esc(prof(p).town) + " PR " + App.esc(prof(p).zip) + '</div></div></div><div class="list-row">' + ic("phone") + '<div class="grow"><div style="font-weight:600">' + tx("Móvil", "Mobile") + '</div><div class="xs subtle">' + App.esc(p.phone) + '</div></div></div><div class="list-row" data-portal-lic>' + ic("id") + '<div class="grow"><div style="font-weight:600">' + tx("Licencia de armas", "Gun license") + '</div><div class="xs subtle"><span class="mono">' + App.lic(m).masked + "</span> · " + (App.lic(m).exp ? tx("vence ", "expires ") + App.fd(App.lic(m).exp) : "—") + '</div></div><a class="small" href="#licencia">' + tx("Ver", "View") + '</a></div><div class="list-row">' + ic("mail") + '<div class="grow"><div style="font-weight:600">Email</div><div class="xs subtle">' + p.email + '</div></div><span class="toggle is-on is-locked" aria-hidden="true"></span></div><div class="list-row">' + ic("sms") + '<div class="grow"><div style="font-weight:600">' + tx("Mensajes de texto", "Text messages") + '</div><div class="xs subtle">' + (p.sms === false ? tx("Sin consentimiento · solo email", "No consent · email only") : tx("Aceptado · responde STOP para salir", "Opted in · reply STOP to opt out")) + '</div></div><span class="toggle' + (p.sms === false ? "" : " is-on") + ' is-locked" aria-hidden="true"></span></div><div class="list-row">' + ic("globe") + '<div class="grow"><div style="font-weight:600">' + tx("Idioma", "Language") + '</div><div class="xs subtle">' + tx("Emails, textos y recibos", "Emails, texts and receipts") + '</div></div><span class="small" style="font-weight:600">' + (p.pref === "en" ? tx("Inglés", "English") : tx("Español", "Spanish")) + "</span></div></div></div>" +
      licSection(m) +
      '<div id="pagos"><div class="sec-head"><div class="m-section-title">' + tx("Visitas y pagos", "Visits & payments") + '</div></div><div class="m-card">' + (hist || '<div class="list-row xs subtle">' + tx("Sin actividad todavía", "No activity yet") + "</div>") + "</div></div></div>" +
      '<nav class="tabbar"><a class="is-active" href="portal.html?m=' + m.id + '">' + ic("home") + "<span>" + tx("Inicio", "Home") + '</span></a><a href="card.html?m=' + m.id + '">' + ic("id") + "<span>" + tx("Tarjeta", "Card") + '</span></a><a href="#hogar">' + ic("users") + "<span>" + tx("Hogar", "Household") + '</span></a><a href="#licencia">' + ic("id") + "<span>" + tx("Licencia", "License") + '</span></a><a href="#perfil">' + ic("user") + "<span>" + tx("Perfil", "Profile") + "</span></a></nav>";
    return App.mobileShell({ step: "card", sub: tx("Portal del miembro", "Member portal"), content: '<div class="m-page">' + body + '<div class="m-foot" style="padding-top:12px">' + App.powered() + "</div></div>",
      guide: tx("Inicio de sesión sin contraseña (enlace por email o texto). Toca la tarjeta para abrir el QR que se escanea en recepción.", "Passwordless sign-in (link by email or text). Tap the card to open the QR the front desk scans.") });
  }
  App.page({
    render: render,
    title: function () { return tx("Mi membresía", "My membership"); },
    handlers: {
      editProfile: function () {
        var w = who(), p = w.p, me = w.m, pr = prof(p), LI = App.lic(me), F = { phone: me.phone || p.phone, email: me.email || p.email, town: pr.town, zip: pr.zip, emer: pr.emer, pref: me.pref || p.pref || "es", licExp: LI.exp || "" }, err = "";
        var fld = function (k, label, attrs, cls) { return '<label class="pf' + (cls ? " " + cls : "") + '"><span class="pf-l">' + label + '</span><input class="input" data-pf="' + k + '" value="' + App.esc(F[k]) + '"' + (attrs || "") + "></label>"; };
        App.modal({ render: function () {
          return '<div class="modal-head"><h2>' + tx("Editar mis datos", "Edit my details") + '</h2><button type="button" class="icon-btn" data-act="closeModal" aria-label="' + tx("Cerrar", "Close") + '">' + ic("x") + '</button></div><div class="modal-body stack-3"><div class="edit-grid">' +
            fld("phone", tx("Móvil", "Mobile"), ' inputmode="tel" autocomplete="tel"') + fld("email", "Email", ' inputmode="email" autocomplete="email"') +
            fld("town", tx("Municipio", "Town"), "") + fld("zip", tx("Código postal", "ZIP code"), ' inputmode="numeric" maxlength="5"') +
            fld("emer", tx("Contacto de emergencia", "Emergency contact"), "", "full") +
            '<div class="pf"><span class="pf-l">' + tx("Licencia de armas", "Gun license") + '</span><div class="input ro-input mono">' + LI.masked + '</div><span class="xs subtle">' + tx("El número no cambia al renovar", "The number stays the same on renewal") + "</span></div>" + fld("licExp", tx("Vence la licencia", "License expires"), ' type="date"') +
            '<label class="pf full"><span class="pf-l">' + tx("Idioma de emails, textos y recibos", "Language for emails, texts and receipts") + '</span><select class="select input" data-pf="pref"><option value="es"' + (F.pref === "es" ? " selected" : "") + '>Español</option><option value="en"' + (F.pref === "en" ? " selected" : "") + ">English</option></select></label></div>" +
            (err ? '<div class="help is-error" role="alert">' + ic("alert") + "<span>" + err + "</span></div>" : "") +
            '<div class="xs subtle">' + tx("Los consentimientos de texto se cambian respondiendo STOP/START; quedan registrados con fecha y hora.", "Text consent changes by replying STOP/START; each change is logged with date and time.") + '</div></div><div class="modal-foot"><button type="button" class="btn btn-secondary" data-act="closeModal">' + tx("Cancelar", "Cancel") + '</button><button type="button" class="btn btn-primary" data-act="pfSave">' + tx("Guardar", "Save") + "</button></div>";
        } });
        App.handlers.pfSave = function () {
          document.querySelectorAll("[data-pf]").forEach(function (el) { F[el.dataset.pf] = el.value.trim(); });
          if (F.phone.replace(/\D/g, "").length !== 10) err = tx("Escribe un móvil de 10 dígitos.", "Enter a 10-digit mobile.");
          else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(F.email)) err = tx("Escribe un email válido.", "Enter a valid email.");
          else if (!/^\d{5}$/.test(F.zip)) err = tx("Código postal de 5 dígitos.", "5-digit ZIP code.");
          else if (!/^\d{4}-\d{2}-\d{2}$/.test(F.licExp)) err = tx("Escribe la fecha de vencimiento de tu licencia.", "Enter your license expiry date.");
          else err = "";
          if (err) { App.renderModal(); return; }
          var lic = Object.assign({}, me.lic || {}, { exp: F.licExp }); delete F.licExp;
          App.update(p.id, F); App.update(me.id, { lic: lic }); App.closeModal(); App.keepScroll = true; App.rerender(); App.toast(tx("Datos guardados", "Details saved"));
        };
      },
      licFiled: function () { var w = who(); App.setLicFiled(w.m.id, !w.m.licFiled); App.keepScroll = true; App.rerender(); App.toast(App.member(w.m.id).licFiled ? tx("Renovación radicada · avisos en pausa", "Renewal filed · reminders paused") : tx("Avisos reactivados", "Reminders back on")); },
      toggleAuto: function () {
        var w = who(), p = w.p;
        if (p.autorenew) { App.update(p.id, { autorenew: null }); App.keepScroll = true; App.rerender(); App.toast(tx("Auto-renovación cancelada", "Auto-renew cancelled")); return; }
        App.modal({ render: function () {
          return '<div class="modal-head"><h2>' + tx("Activar auto-renovación", "Turn on auto-renew") + '</h2><button type="button" class="icon-btn" data-act="closeModal" aria-label="' + tx("Cerrar", "Close") + '">' + ic("x") + '</button></div><div class="modal-body stack-2"><button type="button" class="pick" data-act="arPick" data-v="paypal"><span class="wm wm-paypal">Pay<b>Pal</b></span><span class="grow">PayPal</span>' + ic("chev-right", "i-sm") + '</button><button type="button" class="pick" data-act="arPick" data-v="card">' + ic("card") + '<span class="grow">' + tx("Tarjeta (Visa •••• 1111)", "Card (Visa •••• 1111)") + "</span>" + ic("chev-right", "i-sm") + '</button><div class="callout">' + ic("lock") + "<span>" + tx("ATH Móvil no permite pagos recurrentes.", "ATH Móvil doesn't support recurring payments.") + "</span></div></div>";
        } });
        App.handlers.arPick = function (el) { App.update(p.id, { autorenew: el.dataset.v }); App.closeModal(); App.keepScroll = true; App.rerender(); App.toast(tx("Auto-renovación activada (simulado)", "Auto-renew turned on (simulated)")); };
      }
    }
  });
})();
