/* Range settings (working in the prototype, saved in this browser and cleared by "Reset demo"):
   gun-license rule (read-only: expired / suspended / revoked always blocks, per Reg. 9172 Art. 3.05), closing time for the
   end-of-day warning, the membership reminder schedule, and the gun-license reminder timeline with its channels
   (email, push, in-app on; SMS optional and off by default because carriers restrict firearms-related texting). */
(function () {
  var tx = App.tx, ic = App.ic;
  function render() {
    var t = App.ten(), st = App.settings(), ch = st.licCh;
    var sched = function (items, chan) { return '<ol class="sched">' + items.map(function (x) { return '<li><span class="sched-d">' + x[0] + '</span><span class="small">' + x[1] + '</span><span class="xs subtle row" style="gap:4px">' + ic(x[2] === "mail" ? "mail" : "sms", "i-xs") + x[3] + "</span></li>"; }).join("") + "</ol>" + (chan ? '<p class="xs subtle" style="margin-top:8px">' + chan + "</p>" : ""); };
    var em = tx("Solo email", "Email only"), both = tx("Texto + email", "Text + email");
    var mem = sched([["30", tx("días antes", "days before"), "mail", em], ["14", tx("días antes", "days before"), "mail", em], ["7", tx("días antes", "days before"), "sms", both], ["1", tx("día antes", "day before"), "sms", both], ["0", tx("día de vencimiento", "expiry day"), "sms", both], ["+3", tx("en gracia", "in grace"), "sms", both], ["+" + (t.grace + 1), tx("vencida", "lapsed"), "sms", both]], tx("Con auto-renovación: solo el aviso de cobro 7 días antes.", "On auto-renew: only the charge notice 7 days before."));
    var chNames = [ch.email ? "Email" : "", ch.push ? "Push" : "", ch.app ? tx("En la app", "In-app") : "", ch.sms ? "SMS" : ""].filter(Boolean).join(" + ") || tx("Ningún canal", "No channel");
    var why = { 180: tx("ya puede renovar", "renewal opens"), 0: tx("desde mañana no puede tirar", "from tomorrow: may not shoot"), "-25": tx("antes de las multas", "before fines"), "-60": tx("multa $25/mes", "$25/month fine"), "-120": tx("multa $25/mes", "$25/month fine"), "-150": tx("aviso de cancelación", "cancellation warning") };
    var licRows = '<ol class="sched">' + App.LIC_DAYS.map(function (d) { return '<li><span class="sched-d">' + (d > 0 ? d : d === 0 ? "0" : "+" + -d) + '</span><span class="small">' + (d > 0 ? tx("días antes", "days before") : d === 0 ? tx("día de vencimiento", "expiry day") : tx("días después", "days after")) + (why[d] ? '<span class="xs subtle"> · ' + why[d] + "</span>" : "") + '</span><span class="xs subtle">' + chNames + "</span></li>"; }).join("") + "</ol>";
    var sw = function (k, label, sub, icon) { return '<div class="set-row ch-row"><span class="ch-ic">' + ic(icon, "i-sm") + '</span><div class="grow"><div style="font-weight:650">' + label + "</div>" + (sub ? '<div class="xs subtle">' + sub + "</div>" : "") + '</div><button type="button" class="tgl" role="switch" aria-checked="' + !!ch[k] + '" data-act="ch" data-v="' + k + '"><span class="tgl-k"></span><span class="tgl-t">' + (ch[k] ? tx("Activo", "On") : tx("Apagado", "Off")) + "</span></button></div>"; };
    var chans = sw("email", "Email", tx("Con acentos; informativo (sin promociones)", "Accents OK; informational (no promotions)"), "mail") + sw("push", tx("Notificación push", "Push notification"), tx("En el teléfono del miembro (app del club)", "On the member's phone (range app)"), "bell") + sw("app", tx("Aviso en la app y el portal", "In-app & portal notice"), tx("Tarjeta en el portal del miembro", "Card in the member portal"), "user") +
      sw("sms", tx("Texto (SMS) · opcional", "Text (SMS) · optional"), tx("Solo con consentimiento de SMS. Sin acentos, 1 segmento (≤160).", "Only with SMS consent. No accents, 1 segment (≤160)."), "sms") +
      '<div class="callout warn" data-sms-note>' + ic("alert") + "<span>" + tx("Las operadoras restringen los mensajes relacionados con armas de fuego (CTIA «SHAFT»; Twilio no los permite). Pendiente de Legal y del proveedor antes de activar SMS.", "Carriers restrict firearms-related messaging (CTIA “SHAFT”; Twilio doesn't allow it). Pending Legal and vendor clearance before turning SMS on.") + "</span></div>";
    var body = '<div class="page-head"><div><h1>' + tx("Ajustes del club", "Range settings") + "</h1><p>" + t.name + tx(" · se guardan en este navegador; «Reiniciar demo» los restablece.", " · saved in this browser; “Reset demo” restores them.") + "</p></div></div>" +
      '<div class="set-grid"><div class="stack-4"><section class="card"><div class="card-header"><div><h2>' + tx("Reglas de entrada", "Check-in rules") + '</h2><div class="small subtle">' + tx("Se aplican en recepción y en el quiosco", "Applied at the front desk and the kiosk") + '</div></div></div><div class="card-body stack-4">' +
      '<div class="set-row ro" data-lic-rule><span class="ch-ic" style="background:var(--bad-50,#FDECEA);color:var(--bad-600)">' + ic("ban", "i-sm") + '</span><div class="grow"><div style="font-weight:650">' + tx("Licencia de armas vencida, suspendida o revocada", "Gun license expired, suspended or revoked") + '</div><div class="small muted">' + tx("Siempre bloquea la entrada; no hay excepción desde recepción (Reglamento 9172, Art. 3.05). Si vence hoy: aviso, puede entrar.", "Always blocks check-in; no front-desk override (Reglamento 9172, Art. 3.05). Expiring today: warning, may check in.") + '</div></div><span class="badge badge--lapsed">' + tx("Bloquear", "Block") + "</span></div>" +
      '<div class="divider"></div><div class="set-row"><div class="grow"><div style="font-weight:650">' + tx("Hora de cierre", "Closing time") + '</div><div class="small muted">' + tx("Después de esta hora (AST) el panel y el registro avisan quién sigue registrado.", "After this time (AST) the dashboard and log warn who's still signed in.") + '</div></div><input class="input" type="time" id="close-time" value="' + App.esc(st.close || t.close) + '" style="width:140px"></div>' +
      '<div class="set-row ro"><div class="grow"><div style="font-weight:650">' + tx("Período de gracia de la membresía", "Membership grace period") + '</div><div class="small muted">' + tx("Puede entrar durante la gracia", "May check in during grace") + '</div></div><strong>' + t.grace + tx(" días", " days") + '</strong></div><div class="set-row ro"><div class="grow"><div style="font-weight:650">' + tx("Edad mínima", "Minimum age") + '</div></div><strong>' + t.minAge + "</strong></div></div></section>" +
      '<section class="card"><div class="card-header"><div><h2>' + tx("Membresía · recordatorios", "Membership · reminders") + '</h2><div class="small subtle">' + tx("Se envían cada mañana; en la demo, desde el panel", "Sent every morning; in the demo, from the dashboard") + '</div></div><a class="btn btn-secondary btn-sm" href="outbox.html">' + ic("send", "i-sm") + tx("Ver mensajes", "View messages") + '</a></div><div class="card-body">' + mem + "</div></section></div>" +
      '<section class="card" id="recordatorios"><div class="card-header"><div><h2 class="row" style="gap:6px">' + ic("id", "i-sm") + tx("Licencia de armas · avisos", "Gun license · reminders") + '</h2><div class="small subtle">' + tx("Desde 6 meses antes (cuando ya se puede renovar) hasta 150 días después", "From 6 months before (when renewal opens) to 150 days after") + '</div></div></div><div class="card-body stack-3"><div class="label">' + tx("Canales", "Channels") + "</div>" + chans + '<div class="divider"></div><div class="label">' + tx("Calendario", "Timeline") + "</div>" + licRows +
      '<p class="xs subtle">' + tx("«Renovación radicada» (en el portal o en recepción) pone en pausa los avisos de ese miembro.", "“Renewal filed” (in the portal or at the desk) pauses that member's reminders.") + "</p></div></section></div>";
    return App.staffShell(location.hash === "#recordatorios" ? "reminders" : "settings", body);
  }
  App.page({
    render: render,
    title: function () { return tx("Ajustes del club", "Range settings"); },
    init: function () { if (location.hash) { var el = document.querySelector(location.hash); if (el) el.scrollIntoView(); } },
    after: function () { var c = document.getElementById("close-time"); if (c) c.addEventListener("change", function () { if (/^\d{2}:\d{2}$/.test(c.value)) { App.setSetting("close", c.value); App.toast(tx("Hora de cierre: ", "Closing time: ") + App.hm(c.value)); } }); },
    handlers: {
      ch: function (el) {
        var k = el.dataset.v, ch = App.settings().licCh; ch[k] = !ch[k];
        App.ts().events.push({ type: "setting", at: Date.now(), k: "licCh." + k, v: ch[k] }); App.save(); App.keepScroll = true; App.rerender();
        App.toast((k === "sms" ? "SMS" : k === "push" ? "Push" : k === "app" ? tx("En la app", "In-app") : "Email") + (ch[k] ? tx(" activado para avisos de licencia", " on for license reminders") : tx(" apagado para avisos de licencia", " off for license reminders")));
      }
    }
  });
})();
